Raise minimum tested toolchain to rust 1.57
Required by the transitive dependency on os_str_bytes:

    error: package `os_str_bytes v6.2.0` cannot be built because it
    requires rustc 1.57.0 or newer, while the currently active rustc
    version is 1.56.1