Raise minimum compiler in CI to rustc 1.54
Required by use of extended_key_value_attributes in clap_derive.

    error[E0658]: arbitrary expressions in key-value attributes are unstable
      --> github.com-1ecc6299db9ec823/clap_derive-3.0.6/src/lib.rs:16:10
       |
    16 | #![doc = include_str!("../README.md")]
       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^