Bump oldest rustc tested to 1.56.1
Required by the `rust-version = "1.56.1"` declaration in indexmap's
Cargo.toml.

    error: package `indexmap v1.9.0` cannot be built because it
    requires rustc 1.56.1 or newer, while the currently active rustc
    version is 1.56.0