Raise minimum compiler in CI to rustc 1.49
Required by use of std::hint::spin_loop in parking_lot.

    error[E0658]: use of unstable library feature 'renamed_spin_loop'
      --> github.com-1ecc6299db9ec823/parking_lot_core-0.8.4/src/spinwait.rs:16:9
       |
    16 |         hint::spin_loop()
       |         ^^^^^^^^^^^^^^^