Update minimum supported compiler to rustc 1.46
Required by the transitive dependency on the bitflags crate.

    error[E0658]: `if` is not allowed in a `const fn`
      --> github.com-1ecc6299db9ec823/clap-2.33.3/src/app/settings.rs:7:1
       |
    7  | / bitflags! {
    8  | |     struct Flags: u64 {
    9  | |         const SC_NEGATE_REQS       = 1;
    10 | |         const SC_REQUIRED          = 1 << 1;
    ...  |
    51 | |     }
    52 | | }
       | |_^
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)