Raise minimum tested compiler to 1.74
Required by newest versions of clap and clap_derive.

    error: package `clap_derive v4.5.0` cannot be built because it requires rustc 1.74 or
    newer, while the currently active rustc version is 1.70.0
    Either upgrade to rustc 1.74 or newer, or use
    cargo update -p clap_derive@4.5.0 --precise ver
    where `ver` is the latest version of `clap_derive` supporting rustc 1.70.0